<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "get_text_contents"
 *
 * Auto generated by Extension Builder 2014-05-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Get text contents',
	'description' => 'CLI tool to fetch all text elements from each page and serve it to you as an CSV',
	'category' => 'misc',
	'author' => 'Daniel Dorndorf',
	'author_email' => 'dorndorf@dreipunktnull.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.1'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		)
	)
);